<?xml version="1.0" encoding="utf-8"?><Database Name="BloodBankDB" Class="BloodBankDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\BloodBankDB.mdf;Integrated Security=True" SettingsObjectName="BloodBank.Properties.Settings" SettingsPropertyName="BloodBankDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BloodGroup" Member="BloodGroups">
    <Type Name="BloodGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="BloodGroup_Donor" Member="Donors" ThisKey="Id" OtherKey="bloodGroup" Type="Donor" />
    </Type>
  </Table>
  <Table Name="dbo.Province" Member="Provinces">
    <Type Name="Province">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProvinceName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Province_City" Member="Cities" ThisKey="Id" OtherKey="Province" Type="City" />
      <Association Name="Province_Donor" Member="Donors" ThisKey="Id" OtherKey="province" Type="Donor" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Province" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="City_Donor" Member="Donors" ThisKey="Id" OtherKey="city" Type="Donor" />
      <Association Name="Province_City" Member="Province1" ThisKey="Province" OtherKey="Id" Type="Province" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Donor" Member="Donors">
    <Type Name="Donor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bloodGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="province" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="bloodAvailable" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BloodGroup_Donor" Member="BloodGroup1" ThisKey="bloodGroup" OtherKey="Id" Type="BloodGroup" IsForeignKey="true" />
      <Association Name="Province_Donor" Member="Province1" ThisKey="province" OtherKey="Id" Type="Province" IsForeignKey="true" />
      <Association Name="City_Donor" Member="City1" ThisKey="city" OtherKey="Id" Type="City" IsForeignKey="true" />
    </Type>
  </Table>
</Database>